### ISSUE TITLE
thread 'main' panicked at hyprscratch-0.4.2/src/config.rs:173:26

### ISSUE THREAD

**Issue by tsundokul** [sashetophizika/hyprscratch#2] opened 2024-08-25 07:53 UTC
It looks like it panics when parsing my config;
[hyprland.txt](https://github.com/user-attachments/files/16739408/hyprland.txt)

```
stack backtrace:
   0:     0x5640906048e5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::had1e383e8ca8ed48
   1:     0x56409062766b - core::fmt::write::h34bcc2a89ef12d61
   2:     0x5640906025af - std::io::Write::write_fmt::h44df6dad0c07d388
   3:     0x5640906046be - std::sys_common::backtrace::print::h4eb209846b9240a8
   4:     0x564090605979 - std::panicking::default_hook::{{closure}}::h090f578746e3f541
   5:     0x5640906056bd - std::panicking::default_hook::hcbbeb583e7bf29cb
   6:     0x564090605e13 - std::panicking::rust_panic_with_hook::ha18f96280878d92e
   7:     0x564090605cf4 - std::panicking::begin_panic_handler::{{closure}}::h2561938f8a020024
   8:     0x564090604da9 - std::sys_common::backtrace::__rust_end_short_backtrace::he770c6f57060202d
   9:     0x564090605a27 - rust_begin_unwind
  10:     0x5640904e8f53 - core::panicking::panic_fmt::hb5158d7a4d937af4
  11:     0x5640904e9107 - core::panicking::panic_bounds_check::hc2caeec04494e035
  12:     0x5640904f0797 - hyprscratch::config::parse_config::hac41b77867de62a9
  13:     0x5640904eea38 - hyprscratch::config::Config::new::hb73179df1a650de5
  14:     0x5640904f4731 - hyprscratch::daemon::initialize::h05fc8686c53d539d
  15:     0x5640904fd2be - hyprscratch::main::h76783da67fa02e91
  16:     0x5640904fccd6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h458335665d0e46d5
  17:     0x5640904fa475 - std::rt::lang_start::{{closure}}::hf4cbe4dc10d3726e
  18:     0x5640905fe8d0 - std::rt::lang_start_internal::h189e9641b3b719d4
  19:     0x5640904fd5d5 - main
  20:     0x7fdfaea2bc8a - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  21:     0x7fdfaea2bd45 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  22:     0x5640904e95c1 - _start
  23:                0x0 - <unknown>
  ```

**Comment by sashetophizika** [comment] 2024-08-25 10:04
Could you paste your config? I need just the lines with `hyprscratch` on them.

**Comment by tsundokul** [comment] 2024-08-25 10:05
> Could you paste your config? I need just the lines with `hyprscratch` on them.

yeah, check the link from the first post, it's attached as a txt file

**Comment by sashetophizika** [comment] 2024-08-25 10:20
The issue is currently fixed on main, I am waiting for a new release of `hyprland-rs` to make one myself. For now just clone and compile.

**Closed** 2024-08-26 15:47 UTC
